# Generated by Django 4.1.2 on 2022-10-21 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32, verbose_name='título')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
            ],
        ),
        migrations.CreateModel(
            name='EtiquetaImportancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32, verbose_name='título')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='título')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField(verbose_name='fecha límite')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha actualización')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.etiquetaestado')),
                ('importancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.etiquetaimportancia')),
            ],
        ),
    ]
