# Generated by Django 4.1.2 on 2022-10-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['fecha_creacion'], 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='etiquetaestado',
            options={'verbose_name_plural': 'Etiquetas de estado'},
        ),
        migrations.AlterModelOptions(
            name='etiquetaimportancia',
            options={'verbose_name_plural': 'Etiquetas de importancia'},
        ),
    ]
